$kind: http-request
url: "{{baseUrl}}/api/applications/1/status"
method: PATCH
headers:
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "status": "APPLIED"
    }
order: 3000
